### ISSUE TITLE
Generate initial data

### ISSUE THREAD

**Issue by zalmanu** [silverapp/silver#140]
Generate some initial data for testing purposes using the predefined factories. The generated data should be loaded automatically after `syncdb`. 

Either make a script which uses the factories and is run after `syncdb` or using the factories generate some data and add it to `initial_data.json`.

**Comment by bogdanpetrea** [comment]
No longer using `initial_data.json`. There's a [seed command](https://github.com/silverapp/silver/blob/master/silver/management/commands/seed.py) though.
