### ISSUE TITLE
Migrate code to be Python 2&3 compatible

### ISSUE THREAD

**Issue by zalmanu** [silverapp/silver#254]

**Comment by OmenApps** [comment]
I suspect there are a number of people interested in a quality billing and payments app like silver, but who are using Django 2.0+ and/or Python 3. Updating to Python 3 would be a huge win for the community, and it looks like PauloPeres's commit might be just wht's needed.

**Comment by bogdanpetrea** [comment]
https://github.com/silverapp/silver/pull/619 :clap:
