### ISSUE TITLE
Improve how the BillingLog is constructed

### ISSUE THREAD

**Issue by zalmanu** [silverapp/silver#262]
Right now, when an invoice/proforma is generated automatically, an entry is created in the `BillingLog` table. However, this way we miss the manual activity (done via the admin). To solve the problem, the `BillingLog` entry could be created when issuing an invoice/proforma and an argument `automatic=True/False` could be passed. This way all the activity (be it manual or automatic) related to a subscription could be tracked.

**Comment by bogdanpetrea** [comment]
We're using `BillingLog` to only keep track of automatic document generation atm.
