### ISSUE TITLE
Provider - Generate monthly totals Bug

### ISSUE THREAD

**Issue by macmichael01** [silverapp/silver#325]
On line 362 of the admin.py file (_compute_monthly_totals method) there appears to be a bug.
The date(s) returned from the query is a string representation. e.g - '2016-06-01'. Line 362 is trying to apply formatting to a string when it should be applying formatting to a date object.

**Comment by bogdanpetrea** [comment]
Seems to work for me. Maybe it got fixed or was a Postgres special case. Reopen if it still reproduces.
