### ISSUE TITLE
Inactive subscription error when calling DocumentGenerator

### ISSUE THREAD

**Issue by macmichael01** [silverapp/silver#327]
When the DocumentGenerator is called with a subscription that is inactive, the following error happens:

```
line 805, in add_total_value_to_document
    if billing_date.month in [self.start_date.month,
AttributeError: 'NoneType' object has no attribute 'month'
>>> DocumentsGenerator().generate(subscription=s, billing_date=timezone.now().date())
```

This is likely a state that you should never be in when calling the DocumentGenerator. Better error handling for this case perhaps?

**Comment by bogdanpetrea** [comment]
This is not available anymore.
