### ISSUE TITLE
Deprecate django_xhtml2pdf in favor of weasyprint

### ISSUE THREAD

**Issue by voughtdq** [silverapp/silver#330]
html5lib has made changes which cause xhtml2pdf to break. The "fix" is to change _inputstream.py back to inputstream.py **OR** don't update to the latest html5lib.

In light of this change, now might be a good time to deprecate django_xhtml2pdf in favor of weasyprint (as recommended by the lead developer on the xhtml2pdf project). 

I'll work on adding the functionality to use weasyprint as an alternative. I don't intend on replacing xhtml2pdf at this time since it could mess with others' workflow.

**Comment by macmichael01** [comment]
Here is the specific version right before the breakage for those who need a quick workaround:

`pip install -e git+https://github.com/html5lib/html5lib-python@8db5828d3624d0892f0d5903d089972dce6c48f0#egg=html5lib`

**Comment by bogdanpetrea** [comment]
Currently xhtml2pdf is back to being maintained, and we encountered some CSS issues when we tried out Weasyprint a year ago.
