### ISSUE TITLE
Transaction's pay url shouldn't be a hidden gem

### ISSUE THREAD

**Issue by vtemian** [silverapp/silver#428]
In order to install and configure silver with transactions, you would need to add 
```python
from silver.views import pay_transaction_view


urlpatterns += [
    url(r'pay/(?P<transaction_uuid>[0-9a-z-]+)/$',                              
        pay_transaction_view, name='pay-transaction')                           
]
```
to your urls settings.

**Comment by bogdanpetrea** [comment]
It's already there: https://github.com/silverapp/silver/blob/master/silver/urls.py#L30

**Comment by vtemian** [comment]
My problem is how to include it in my application?

I can't use `url(r'^', include('silver.urls')),` because all urls from https://github.com/silverapp/silver/blob/master/silver/urls.py#L30 will be included.

It's not an API related url and is a silver specific one.

Maybe we restructure the urls from silver and remove those which are not django app specific (like admin and api-auth).
```
urlpatterns = [
    url(r'api/', include('silver.api.urls')),
    url(r'pay/(?P<transaction_uuid>[0-9a-z-]+)/$',
        pay_transaction_view, name='pay-transaction')
]
```
In this way will be really easy to include silver like
```python
urlpatterns = [
    url(r'^', include('silver.urls'))
```
