### ISSUE TITLE
Have only one billing email per customer

### ISSUE THREAD

**Issue by vtemian** [silverapp/silver#436]
Other applications which implements silver can use multiple emails (via customer's meta field), if they have those kind of needs.

**Comment by calind** [comment]
If there multiple emails per `Customer` it can be hard to reason about when implementing payment methods which accept only on billing email. I think that one billing email per customer show be the way to go, and let api consumers or payment method implementers save those multiple emails in `Customer` and `PaymentMethod` metadata fields.
