### ISSUE TITLE
install error 'module' object has no attribute 'ModelSelect2'

### ISSUE THREAD

**Issue by allox** [silverapp/silver#514]
Trying to install Silver, but getting this error :
```

.../local/lib/python2.7/site-packages/silver/admin.py", line 882, in Meta
    'invoice': autocomplete.ModelSelect2(
AttributeError: 'module' object has no attribute 'ModelSelect2'
```

**Comment by bogdanpetrea** [comment]
Hi @allox 
Make sure you have installed `django-autocomplete-light` and that [these 2 apps](https://github.com/silverapp/silver/blob/master/settings.py#L41) before `django.contrib.admin` and `grappelli` if present as stated [here](http://django-autocomplete-light.readthedocs.io/en/master/install.html).

**Comment by allox** [comment]
thanks. it works.

**Comment by bogdanpetrea** [comment]
You're welcome!
