### ISSUE TITLE
get_model import bug

### ISSUE THREAD

**Issue by macmichael01** [silverapp/silver#524]
I realize that Django 1.10 is not yet support  as this is a 1.10 bug but we found an import bug under.

> models/documents/invoices.py
> models/transactions/transaction.py
```
from django.db.models.loading import get_model

# should be:
try:
    from django.db.models.loading import get_model
except ImportError:
    from django.apps import apps
    get_model = apps.get_model
```

**Comment by bogdanpetrea** [comment]
Not available anymore.
