### ISSUE TITLE
Furthering Development

### ISSUE THREAD

**Issue by macmichael01** [silverapp/silver#531]
Hello, I've been following this project for a while now and I am very interested in seeing the further development of this app. I would like to learn more about what's in the backlog (aside from github) and to see if there is any way that we can contribute to this app. Dedicated developer resources perhaps? Is there someone I can speak to (core developers) who is directly in charge of this app?

**Comment by bogdanpetrea** [comment]
Hi @macmichael01,

Roughly what we have in mind for the next couple of months is:
* improving the recurring payments system
* implementing split payments
* extracting the PDF generation as a task
* updating to Django 1.11
* writing statistics / graphs specifications

As for contributing, we accept pull requests for any of our opened issues.
If you wish to speak with me,  you can also find me at bogdan@presslabs.com
