### ISSUE TITLE
Required PAYMENT_PROCESSORS setting not in install documentation

### ISSUE THREAD

**Issue by LordElsinore** [silverapp/silver#589]
After installing silver via pip and following the rest of the setup instructions from the readme, I'm unable to run the migrate or start the service because a PAYMENT_PROCESSORS section is required in the settings file.  I haven't been able to find what this should look like.

**Comment by bogdanpetrea** [comment]
Hi @LordElsinore,
Here's an example https://github.com/silverapp/silver/blob/master/settings.py#L156. If you don't plan on using payments you may just add an empty dict, like `PAYMENT_PROCESSORS = {}`.
