### ISSUE TITLE
Create new Payment processors Documentation

### ISSUE THREAD

**Issue by PauloPeres** [silverapp/silver#606]
Hi Guys!!!
First of All thank you for this impressive tools built on the best Framework ever :D 

I want to use Silver for my company, but we are from Brasil e we need to implement other Payment Processors in the mix and obviously share with community! (I'm also updating Silver to user python 3.x and Django 2.0, i have done 95% of the job, just finishing some tests, will also share that if you guys)

My question is, could someone from the guys who created Silver write a small documentation on how to build new Payment Processors Apps to work with silver?

**Comment by bogdanpetrea** [comment]
Hi @PauloPeres,

First of all, sorry for the late reply. I somehow managed to miss recent notifications from this project.

I'm happy to see you are interested in using Silver, and I'll gladly review your Pull Request.

Better documentation is pretty much always a good idea and I can see why documenting the procedure of adding new Payment Processors is important. I will try to come up with some guidance during the following days!

Until then, here are some references for Payment Processors:
https://www.presslabs.org/silver/docs/resources/#payment-processor
https://www.presslabs.org/silver/docs/payment-processors/

There's also some improvements that could be made tegarding the Payments part of Silver, so if you have any suggestions feel free to open an issue.

**Comment by bogdanpetrea** [comment]
Here's a guide draft https://github.com/silverapp/silver/blob/edeb0541e56caf082dd55fd3e965c6f6882cbbf3/docs/documentation/guides/adding-a-new-payment-processor.md. It's not yet finished, but it might be of help.

**Comment by bogdanpetrea** [comment]
You can find the final form [here](https://github.com/silverapp/silver/blob/master/docs/guides/adding-a-new-payment-processor.md) and should also be up soon on https://www.presslabs.com/code/silver/.
