### ISSUE TITLE
Offset issue

### ISSUE THREAD

**Issue by bogdandaringa** [silverapp/silver#608]
Good Morning, 

Here is my query. 
https://api.ncrsilver.com/Inventory/Items?store_number=1&include_available_online_only=True&offset=2500&limit=5000 

My timeout is set to infinity, bigger than one setup in the server. 
I do not get a result set from you server. It times out after 30 minutes. 
Please advise how to retrieve around 6000 records. 
What are the optimal parameters to pass. 

After extensive tests and research it seams that offset value is the issue. 
Once offset value increases to 2500, timeout occurs. 

I have tested smaller "limit", too. Ranging from 50 to 5000. It times out at offset > 2000/2500. 
What are the optimal values for the link above? 

It would help a lot if you can please provide sample Csharp code to retrieve data above in a efficient way. What libraries do you recommend? 
Let me know if you need other information. I would like to fix this as soon possible. 

Please advise. 

Thanks in advance, 
Bogdan Daringa 
Programmer 
Beverage Media Group 
O: 201-820-4914 
C: 908-770-3252

**Comment by bogdanpetrea** [comment]
Hi @bogdandaringa, the URL you have posted doesn't seem to be related to this project. Maybe you are confusing it with another one called "Silver".
