### ISSUE TITLE
Setup not working. Got model import error

### ISSUE THREAD

**Issue by tapas4git** [silverapp/silver#612]
Hi, 
I am using django 1.11 . I have installed the silver and configured it as mentioned but when migrate with the database I got this issue.

__init__.py", line 15, in <module>
    from billing_entities import Customer, Provider
ModuleNotFoundError: No module named 'billing_entities'

**Comment by bogdanpetrea** [comment]
You are probably using Python 3, but Silver only works with Python 2 at the moment.
There is an [open PR](https://github.com/silverapp/silver/pull/607) for Python 3 support, but it hasn't seen any progress lately.
