### ISSUE TITLE
Unable to create PDF invoices without S3

### ISSUE THREAD

**Issue by maxed0ut** [silverapp/silver#620]
Hi, I have installed Silver into an empty app and got it running using the settings suggested by @allox in issue 527.

I mark an invoice for generation OK, but when I try to download it I get an error and no PDF...

MissingSchema at /admin/silver/invoice/
Invalid URL 'None'

I believe the issues relates to SILVER_DOCUMENT_STORAGE = None

The only other examples I can find for this are for S3, but I don't have S3.

I noticed that in issue 114 (in 2015) https://github.com/silverapp/silver/issues/114 the 'hard' dependency on S3 was removed, but I can't seem to work out how. 

Is this an issue or can you let me, and the rest of the non-S3 world, know how to switch to the local file storage system please? I would simply like to generate a PDF for a user to view/download in the browser

Your help is much appreciated.

**Comment by bogdanpetrea** [comment]
Hi @maxed0ut,
Silver has some tasks, including the PDF generation, that are best run asynchronously. Read https://github.com/silverapp/silver#automated-tasks for some info on how you can set them up.

**Comment by maxed0ut** [comment]
Hi @bogdanpetrea 
Thanks for taking a look at this. Yes, I agree, these sorts of tasks are best automated. I looked at the link and saw that it also expects to save the data to S3....
'For specifying the storage used add the SILVER_DOCUMENT_STORAGE setting to your settings file. Example for storing the PDFs on S3:
SILVER_DOCUMENT_STORAGE = (
    'storages.backends.s3boto.S3BotoStorage', [], {
        'bucket': 'THE-AWS-BUCKET',
        'access_key': 'YOUR-AWS-ACCESS-KEY',
        'secret_key': 'YOUR-AWS-SECRET-KEY',
        'acl': 'private',
        'calling_format': 'boto.s3.connection.OrdinaryCallingFormat'
    }
)'
I was using the browser method simply to allow a user to preview an invoice to check if it is appearing correctly. 

Is there a way to use local file storage for either or both as I don't have S3?

Thanks in advance!

**Comment by bogdanpetrea** [comment]
So you're saying that you ran the PDF generation task and you still have no PDF? I'm asking because unless you run `silver.tasks.generate_pdfs`, you won't have a PDF after creating a Billing Document.

AFAIK if you don't use the `SILVER_DOCUMENT_STORAGE` setting, local storage will be used by default. The directory where the PDFs will be stored in this case corresponds to the `MEDIA_ROOT` setting.

**Comment by bogdanpetrea** [comment]
According to [this stackoverflow answer](https://stackoverflow.com/a/5518073) you need to add
```python
urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
```
to your `urls.py` file.
And you also need to have `DEBUG = True` in your settings file, since this only works in debug mode.

**Comment by maxed0ut** [comment]
Hi Bogdan,
Yes, that really helped. I also had to change the ROOT_URLCONF = 'silver.urls' line as that was causing my urls.py project file to be ignored.
I've closed the case, 
Thanks for the help!
