### ISSUE TITLE
Invoice.transaction_xe_rate required to avoid 500 errors, but API doesn't specify this

### ISSUE THREAD

**Issue by rtxanson** [silverapp/silver#627]
Create a new Invoice, and do not specify a `transaction_xe_rate`. Adding entries to the invoice will result in 500 errors on `invoice` endpoints, as the entry totals are summed up with a `null` exchange rate. Either enforcing that `transaction_xe_rate` in validation or setting a default of 1.0 seems like a reasonable fix.

**Comment by bogdanpetrea** [comment]
Hi @rtxanson , thanks for the bug report.
Did you mean to say _update_ instead of "_create_ any old Invoice"?

**Comment by rtxanson** [comment]
I only noticed it while creating, the "any old" was a little colloquial and unclear. Was doing so via the Django REST API web interface. If you need more info I can run drop some sample JSON too.

**Comment by jeromecc** [comment]
Hello!

I just noticed, while trying to create an invoice through the API, that the key "transaction_xe_rate" seems to be required even when when "currency" and "transaction_currency" are set to the same string.

Error is in file /silver/models/documents/entries.py line 80, in total_before_tax_in_transaction_currency
    result = self.total_before_tax * self.document.transaction_xe_rate
TypeError: unsupported operand type(s) for *: 'Decimal' and 'NoneType'

While it's not such a big deal to add
    "transaction_xe_rate": 1.0
in the json data, maybe the code could be enhanced not to require this key for an identical currency?

Also, the documentation is not up to date. I will fix this.

Have a nice day! Thanks.

**Comment by lucifurtun** [comment]
Any news on this issue?

**Comment by bogdanpetrea** [comment]
It's being worked on here: https://github.com/silverapp/silver/pull/631
A big part of that pull request is a major rework on how the tests are written, as they are currently in a sorry state.
I'll try to get it done by next week since it's been open for a while...

**Comment by lucifurtun** [comment]
@bogdanpetrea, any news on this issue?
