### ISSUE TITLE
question about upgrade Django 2

### ISSUE THREAD

**Issue by iris9112** [silverapp/silver#628]
Hi guys!! I read in the issue  #617 
> "Feel free to reopen if you feel like adding Django 2.x support"

I am thinking use Silver for a project, but I need use Django 2 (By request of the client). I see too some issues about this (issue #607). My question is about if anyone is working in this process (version migration). And respect to:

>  "We should also investigate how hard it would be to support Django 1.11 and Django 2.x versions at the same time, as there might be some users still depending on Django 1.11."

I will try to do too. @bogdanpetrea Let me know please.

**Comment by bogdanpetrea** [comment]
Hi @iris9112,

I started adding support for Django 2.x, but I had to put it on hold for a while... at least until I manage to find some spare work time.

I pushed the branch if you want to have a look: https://github.com/silverapp/silver/pull/632

**Comment by iris9112** [comment]
Hi. I understand you. Don't worry. Definitely if I will review it and if I finish before, I let you know. I'm still very new to several things but I have to do it.
very thank you!!

**Comment by jeromecc** [comment]
In the meantime you could do what I am doing: install Silver as an external Django 1.11 app with Python 2.7 and use it from your Django 2.x project through the API.
Once 2.x support is here, it will be easy to dump & restore the data.

**Comment by iris9112** [comment]
If you're right. I was doing that for a while, but now I need other things. And I think "if I have to do it anyway. Why not share it?" I just hope to find the time soon.

**Comment by jeromecc** [comment]
Sure. We should all contribute to the transition to Django 2.x! :-) I was just pointing out a workaround so that people interested in Silver who read this issue are encouraged to try this cool project even if they need to have a working solution right now. My skills about transitioning from earlier versions of Python & Django are limited but I will have a look at this branch https://github.com/silverapp/silver/pull/632 to see if I can help.

**Comment by bogdanpetrea** [comment]
Good news @iris9112, @jeromecc: I got the tests to pass in the #632 branch. 

A few warnings though:
- the tests don't cover all the functionalities of Silver and I haven't fiddled with a running instance using this branch
- it's very likely that I will redo and force push commits on this branch pretty often

In other words, it's just a preview. Don't use it for anything important.

**Comment by iris9112** [comment]
Hi!! You are amazing @bogdanpetrea ! The warning is understood.
Thank you

**Comment by shurph** [comment]
Hi all, any updates here regarding Django 2 migration?

I'm trying now to launch Silver with Django 2.2 using the experimental `django2x` branch.
During this process I'm facing with few issues. I'll add notes to the PR #632 regarding this.

I'm also wondering could I rely on `django2x` in my experiments?

BTW, @bogdanpetrea could you please rebase your `django2x` to have actual changes from `master`?

**Comment by bogdanpetrea** [comment]
@shurph: I'll try to get it merged this weekend. Please share any issues you encounter when using the `django2x` branch.

**Comment by bogdanpetrea** [comment]
Well, for now I've published a beta release, which you can install and test with `pip install django-silver==0.8b1`.
