### ISSUE TITLE
typo & obsolete keys in users endpoint API documentation

### ISSUE THREAD

**Issue by jeromecc** [silverapp/silver#629]
Hi!

/silver/docs/billing-entities/customers.md

    "<b>name</b>": "John Doe",
    "company": "ACME Inc.",
    "email": "johndoe@acme.inc",
    "<b>address_1</b>": "Funny Road no.4",
    "address_2": null,
    "country": "US",
    "<b>city</b>": "Wilmington",

Typos: bold html tags in key names

Obsolete key: "name" which was divided into "first_name" & "last_name"

Thanks for sharing the code of this great app!

jérôme

**Comment by bogdanpetrea** [comment]
Thanks @jeromecc, I've merged your pull request.
