### ISSUE TITLE
generated pdf contains only the address of an _io.BytesIO object

### ISSUE THREAD

**Issue by jeromecc** [silverapp/silver#635]
Hi!

Python 2.7, Django 1.11, django-silver 0.7.0

Despite my best efforts, all pdf files that I produce from invoices have a size of exaclty 38 bytes & contain something like "<_io.BytesIO object at 0x7f3ef8eb8ad0>".

There is no error or debug message when I generate a pdf file either with the manager or directly in the shell with an invoice instance: invoice.generate_pdf

:-(

My guess is that there is something wrong with the templates but I am not sure. I put a copy of the templates provided in the source in all possible paths.

I guessed from the code that the template path should include the slug name of the provider:
(my test project is called copper, the first 'copper' folder is the one containing manage.py)
...copper/copper/templates/billing_documents/presslabs-srl/invoice_pdf.html

i also used all combinations of
   templates/copper/billing_documents/presslabs-srl/invoice_pdf.html
   templates/silver/billing_documents/presslabs-srl/invoice_pdf.html

etc

my settings module looks like this:

    TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            #PROJECT_ROOT + '/payment_processors/templates/',
            PROJECT_ROOT + '/templates/',
            ],
        'APP_DIRS': True,
        'OPTIONS': {

If someone has an idea what I got wrong, I would appreciate it a lot if she/he could give me an hint.

Thanks a lot!

jérôme

**Comment by jeromecc** [comment]
I can confirm that this looks like a real bug and that it is not related to templates.
I could make it work by modifying generate() in silver/models/documents/pdf.py this way:
```
import cStringIO as StringIO
...
    def generate(self, template, context, upload=True):
        html = template.render(context)
        pdf_file_object = BytesIO()
        pdf = pisa.pisaDocument(
            src=StringIO.StringIO(html.encode("UTF-8")),
            dest=pdf_file_object,
            encoding='UTF-8',
            link_callback=fetch_resources
        )
        
        if not pdf.err:
            if upload:
                self.upload(
                    pdf_file_object=pdf_file_object,
                    filename=context['filename']
                )
        else:
            logger.debug(pdf.err)
            
        return None
```

Can you reproduce the issue? Could it be related to different versions of Python-2.7 or xhtml2pdf or Django used in your production environment and in the repo?
I will check if current tests include verifying the correctness of generated pdf files.

Have a nice day!

jérôme

**Comment by jeromecc** [comment]
i forgot to mention that i also modified upload():

```
    def upload(self, pdf_file_object, filename):
        # the PDF's upload_path attribute needs to be set before calling this method
        with transaction.atomic():
            self.pdf_file.save(filename, pdf_file_object, True)
            self.mark_as_clean()
```

**Comment by bogdanpetrea** [comment]
Some error logs would be nice, yes.
`ContentFile` isn't needed anymore indeed as it was mostly creating the `BytesIO` object for us.

Except for
```python
src=StringIO.StringIO(html.encode("UTF-8"))
# which sould be
src=BytesIO(html.encode('utf-8'))
```
your code looks ok. Maybe you can log with `log.error` in this case.

Could you open a pull request with this fix?

**Comment by jeromecc** [comment]
Sure, I will.

In a later pull request I would like to add code to test the validity of the pdf file. Do you think it's a good idea? Should I try to use...
1. [from PyPDF2 import PdfFileReader] like in https://github.com/xhtml2pdf/xhtml2pdf/blob/ff4097f77e0fc4037a18d38be325537091a5c76f/tests/test_document.py
2. pisa.startViewer() like in https://github.com/xhtml2pdf/xhtml2pdf/blob/master/test/cookbook.py

**Comment by bogdanpetrea** [comment]
I think the `PdfFileReader` method is a bit overkill. I think they use that to test the xhtml2pdf itself.
From what I can tell `startViewer` seems to be used to only view a PDF, not for actual testing.

What we can try is to generate and store a PDF file by freezing inputs (such as time, invoice details etc) to make sure the next time we generate it in a test we can expect the 2 PDFs to match. I think we tried something similar in the past, but it didn't quite work out. But if this doesn't work, our only option remains the `PdfFileReader` method.

Anyway I think it's a good idea to leave this for a later date, so we can release the fix as soon as possible.

**Comment by jeromecc** [comment]
Working on fix. Almost done. PR is coming.

**Comment by jeromecc** [comment]
Ok the fix seems to work (you can have a look it is referenced by GitHub under just above) but now 1 test fails (generate_pdf task):

> __________________________________________________________________________ test_generate_pdf_task __________________________________________________________________________
> 
> mock_http_response = <MagicMock name='BytesIO' id='140081059713680'>, mock_get_template = <MagicMock name='get_template' id='140081067369104'>
> settings = <pytest_django.fixtures.SettingsWrapper object at 0x7f6729d31150>, tmpdir = local('/tmp/pytest-of-user/pytest-0/test_generate_pdf_task0')
> monkeypatch = <_pytest.monkeypatch.MonkeyPatch instance at 0x7f6729f8e518>
> 
>     @pytest.mark.django_db
>     @patch('silver.models.documents.base.BillingDocumentBase.get_template')
>     @patch('silver.models.documents.pdf.BytesIO')
>     def test_generate_pdf_task(mock_http_response, mock_get_template, settings,
>                                tmpdir, monkeypatch):
>         settings.MEDIA_ROOT = tmpdir.strpath
>     
>         invoice = InvoiceFactory.create()
>         invoice.issue()
>     
>         assert invoice.pdf.dirty
>     
>         pisa_document_mock = MagicMock()
>     
>         monkeypatch.setattr('silver.models.documents.pdf.pisa.pisaDocument',
>                             pisa_document_mock)
>     
>         generate_pdf(invoice.id, invoice.kind)
>     
>         # pdf needs to be refreshed as the invoice reference in the test is not the same with the one
>         # in the task
>         invoice.pdf.refresh_from_db()
>     
> >       assert not invoice.pdf.dirty
> E       assert not 2
> E        +  where 2 = <PDF: PDF object>.dirty
> E        +    where <PDF: PDF object> = <Invoice: InvoiceSeries-1 Varga Kocsis Kft => Magyar Horváth NyRT [0.00 RON]>.pdf
> 
> silver/tests/tasks/test_generate_pdfs.py:90: AssertionError
> ================================================================== 1 failed, 297 passed in 32.58 seconds ===================================================================

It's not immediately obvious to me what is wrong. Why is dirty a positive integer rather than a bool?

**Comment by jeromecc** [comment]
I guess there is something wrong going on between django-silver code in functions upload & mark_as_clean and the database that causes the test to fail.
Upload has the argument save set to True. It feels redundant with the many "with transaction.atomic():" blocks. I can't put the finger on the bug though... Could we use django-fsm instead of the in-house 'dirty' solution? I will have another coffee and try to understand why 'dirty' gets incremented and not decremented...

**Comment by bogdanpetrea** [comment]
It's because of the somewhat badly written `test_generate_pdf_task` test that fails. `pisa.pisaDocument` is mocked with MagicMock and because of that `pisa_status.err` evaluates to `True`. 

Below is a version of the test that passes, although we should certainly get rid of the mocks and test for the PDF file to be properly generated. For now it should do though:
```python
@pytest.mark.django_db
def test_generate_pdf_task(settings, tmpdir, monkeypatch):
    settings.MEDIA_ROOT = tmpdir.strpath

    invoice = InvoiceFactory.create()
    invoice.issue()

    assert invoice.pdf.dirty

    pisa_document_mock = MagicMock(return_value=MagicMock(err=False))

    monkeypatch.setattr('silver.models.documents.pdf.pisa.pisaDocument',
                        pisa_document_mock)

    generate_pdf(invoice.id, invoice.kind)

    # pdf needs to be refreshed as the invoice reference in the test is not the same with the one
    # in the task
    invoice.pdf.refresh_from_db()

    assert not invoice.pdf.dirty

    assert invoice.pdf.url == settings.MEDIA_URL + invoice.get_pdf_upload_path()

    assert pisa_document_mock.call_count == 1

    pisa_document_mock.assert_called_once()
```

**Comment by jeromecc** [comment]
Thanks for the tutoring I really appreciate it. I am sending the PR now.
