### ISSUE TITLE
Documentation Link incorrect

### ISSUE THREAD

**Issue by ajaff** [silverapp/silver#651]
The documentation link on the ReadMe _https://www.presslabs.org/silver/docs/_ is being forwarded to _https://www.presslabs.com/news/silver-update/_

**Comment by bogdanpetrea** [comment]
Hi @ajaff,
Thanks for the heads-up. There's been some reworking in our documentation system, and the silver docs broke in the process.
Hopefully we'll fix them soon enough, but until then, the [markdown docs](https://github.com/silverapp/silver/tree/master/docs) could be a temporary alternative.

**Comment by bogdanpetrea** [comment]
The docs are (mostly) back up again. The search functionality is not working yet and some other minor adjustments need to be done as well.
