### ISSUE TITLE
Payment process does not exist in package

### ISSUE THREAD

**Issue by esfandiaryfard** [silverapp/silver#657]
I have downloaded package but when I try to migrate I face this error:
AttributeError: 'Settings' object has no attribute 'PAYMENT_PROCESSORS'
I dont know exactly where is the problem but I have not payment process in my models

**Comment by bogdanpetrea** [comment]
The handling of settings could really use some improvements, but for now you can see here how you can configure the payment processors: https://github.com/silverapp/silver#payment-processors-settings.
So if you don't want to process payments yet, just put 
```python
PAYMENT_PROCESSORS = {}
```
in your settings file.
