### ISSUE TITLE
Adding image in template

### ISSUE THREAD

**Issue by mbhassan** [silverapp/silver#669]
Tried to add an image into the template (document_pdf_base.html) and generate a pdf but keep getting this error.

```
WARNING 2020-01-11 13:43:09,665 tags 1 140567223225672 Need a valid file name!
'<img align="left" alt="" height="40" src="/static/img/msl_logo.png" width="101"/>'
```

have created an img folder in my static folder and placed the file with name 'msl_logo.png' in the img folder.

**Comment by bogdanpetrea** [comment]
Hi @mbhassan ,

If you are using local images you have to wrap the path with the static tag:

```html
{% load staticfiles %}
<img src="{% static 'images/pdf/logo.png' %}">
```

**Comment by mbhassan** [comment]
hmm. Maybe my project structure is messing it up (changed the structure to mimic django-cookiecutter).

**Comment by bogdanpetrea** [comment]
Have you also properly configured the staticfiles? I am using these settings:
```python
# settings.py

BASE_DIR = "full/path/to/project/root"
# see https://docs.djangoproject.com/en/3.0/ref/settings/#static-root
STATIC_ROOT = os.path.join(BASE_DIR, '/static/')
# see https://docs.djangoproject.com/en/3.0/ref/settings/#static-url
STATIC_URL = '/static/'
```

See if you can access the image directly via the browser with the app running. (e.g. `localhost:8000/static/img/msl_logo.png`)

**Comment by bogdanpetrea** [comment]
Hey @mbhassan , any results?

**Comment by bogdanpetrea** [comment]
I'm assuming it worked out in the end.

**Comment by mbhassan** [comment]
sorry for the delay. Managed to get it working. Had changed folder structure to be django cookiecutter so media wasnt set up properly.

@bogdanpetrea should consider switching the project layout to django-cookiecutter.
